using Oracle.DataAccess.Client;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Shapes;

namespace ELREORS
{
    /// <summary>
    /// Interaction logic for Admin_History_Details.xaml
    /// </summary>
    public partial class Admin_History_Details : Window
    {
        DataTable dt = new DataTable();
        string id;
        public Admin_History_Details(string nonota,string id)
        {
            InitializeComponent();
            kodenota.Content = nonota;
            this.id = id;
            load();
        }

        private void load()
        {
            OracleDataAdapter da = new OracleDataAdapter(
                "select d.id, m.id , m.nama as Nama,  d.harga as Harga, d.JUMLAH as Jumlah , d.harga*d.jumlah as Subtotal " +
                "from djual d " +
                "left join menu m on d.id_menu = m.id " +
                $"where d.ID_HEADER={id} ", App.conn);
            da.Fill(dt);
            dgdetail.ItemsSource = dt.DefaultView;
        }

        private void Button_Click(object sender, RoutedEventArgs e)
        {
            int tot = 0;
            foreach (DataRow item in dt.Rows)
            {
                tot+=Convert.ToInt32(item["Subtotal"]);
            }
            tot += (tot / 10); // +perhitungan pajak
            string qry = $"update hjual set total_harga={tot} where id={id}";
            OracleCommand cmd = new OracleCommand(qry, App.conn);
            cmd.ExecuteNonQuery();
            if (tot==0)
            {
                updateStatusHjual(id,4);
            }
            this.Close();
        }

        private void dgdetail_MouseDoubleClick(object sender, MouseButtonEventArgs e)
        {
            int idrow = dgdetail.SelectedIndex;
            if (idrow >= 0)
            {
                string iddjual = dt.Rows[idrow][0].ToString();
                string idmenu = dt.Rows[idrow][1].ToString();
                int harga = Convert.ToInt32(dt.Rows[idrow][3].ToString());
                int jumlah = Convert.ToInt32(dt.Rows[idrow][4].ToString());
                Admin_History_Details_Update w = new Admin_History_Details_Update(id, kodenota.Content.ToString(), iddjual, idmenu, harga, jumlah);
                Close();
                w.ShowDialog();
            }
        }

        private void dgdetail_AutoGeneratedColumns(object sender, EventArgs e)
        {
            dgdetail.Columns[0].Visibility = Visibility.Collapsed;
            dgdetail.Columns[1].Visibility = Visibility.Collapsed;
        }

        public void updateStatusHjual(string id, int status)
        {
            string qry = $"update hjual set status={status} where id={id}";
            OracleCommand cmd = new OracleCommand(qry, App.conn);
            cmd.ExecuteNonQuery();
        }

        private void ButtonVoid_Click(object sender, RoutedEventArgs e)
        {
            OracleCommand cmd = new OracleCommand($"select status from hjual where id={id}", App.conn);
            string result = cmd.ExecuteScalar().ToString();
            if (result == "4")
            {
                updateStatusHjual(id, 3);//jadi editted
                btnVoid.Content = "Void";
            }
            else
            {
                updateStatusHjual(id, 4);
                btnVoid.Content = "Unvoid";
            }
        }

        private void Button_Loaded(object sender, RoutedEventArgs e)
        {
            OracleCommand cmd = new OracleCommand($"select status from hjual where id={id}", App.conn);
            string result = cmd.ExecuteScalar().ToString();
            if (result=="4")
            {
                btnVoid.Content = "Unvoid";
            }
            else
            {
                btnVoid.Content = "Void";
            }
        }
    }
}
